module AcmeAISDK
  module Errors
    class Error < StandardError
      attr_accessor cause: StandardError?
    end

    class ConversionError < AcmeAISDK::Errors::Error
    end

    class APIError < AcmeAISDK::Errors::Error
      attr_accessor url: URI::Generic

      attr_accessor status: Integer?

      attr_accessor body: top?

      def initialize: (
        url: URI::Generic,
        ?status: Integer?,
        ?body: Object?,
        ?request: nil,
        ?response: nil,
        ?message: String?
      ) -> void
    end

    class APIConnectionError < AcmeAISDK::Errors::APIError
      def initialize: (
        url: URI::Generic,
        ?status: nil,
        ?body: nil,
        ?request: nil,
        ?response: nil,
        ?message: String?
      ) -> void
    end

    class APITimeoutError < AcmeAISDK::Errors::APIConnectionError
      def initialize: (
        url: URI::Generic,
        ?status: nil,
        ?body: nil,
        ?request: nil,
        ?response: nil,
        ?message: String?
      ) -> void
    end

    class APIStatusError < AcmeAISDK::Errors::APIError
      def self.for: (
        url: URI::Generic,
        status: Integer,
        body: Object?,
        request: nil,
        response: nil,
        ?message: String?
      ) -> instance

      def initialize: (
        url: URI::Generic,
        status: Integer,
        body: Object?,
        request: nil,
        response: nil,
        ?message: String?
      ) -> void
    end

    class BadRequestError < AcmeAISDK::Errors::APIStatusError
      HTTP_STATUS: 400
    end

    class AuthenticationError < AcmeAISDK::Errors::APIStatusError
      HTTP_STATUS: 401
    end

    class PermissionDeniedError < AcmeAISDK::Errors::APIStatusError
      HTTP_STATUS: 403
    end

    class NotFoundError < AcmeAISDK::Errors::APIStatusError
      HTTP_STATUS: 404
    end

    class ConflictError < AcmeAISDK::Errors::APIStatusError
      HTTP_STATUS: 409
    end

    class UnprocessableEntityError < AcmeAISDK::Errors::APIStatusError
      HTTP_STATUS: 422
    end

    class RateLimitError < AcmeAISDK::Errors::APIStatusError
      HTTP_STATUS: 429
    end

    class InternalServerError < AcmeAISDK::Errors::APIStatusError
      HTTP_STATUS: Range[Integer]
    end
  end

  class Error = AcmeAISDK::Errors::Error

  class ConversionError = AcmeAISDK::Errors::ConversionError

  class APIError = AcmeAISDK::Errors::APIError

  class APIStatusError = AcmeAISDK::Errors::APIStatusError

  class APIConnectionError = AcmeAISDK::Errors::APIConnectionError

  class APITimeoutError = AcmeAISDK::Errors::APITimeoutError

  class BadRequestError = AcmeAISDK::Errors::BadRequestError

  class AuthenticationError = AcmeAISDK::Errors::AuthenticationError

  class PermissionDeniedError = AcmeAISDK::Errors::PermissionDeniedError

  class NotFoundError = AcmeAISDK::Errors::NotFoundError

  class ConflictError = AcmeAISDK::Errors::ConflictError

  class UnprocessableEntityError = AcmeAISDK::Errors::UnprocessableEntityError

  class RateLimitError = AcmeAISDK::Errors::RateLimitError

  class InternalServerError = AcmeAISDK::Errors::InternalServerError
end
