module AcmeAISDK
  module Models
    type file_file_create_params =
      {
        file: (IO | StringIO),
        description: String,
        processing_options: AcmeAISDK::Models::FileFileCreateParams::ProcessingOptions
      }
      & AcmeAISDK::Internal::Type::request_parameters

    class FileFileCreateParams < AcmeAISDK::Internal::Type::BaseModel
      extend AcmeAISDK::Internal::Type::RequestParameters::Converter
      include AcmeAISDK::Internal::Type::RequestParameters

      attr_accessor file: IO | StringIO

      attr_reader description: String?

      def description=: (String) -> String

      attr_reader processing_options: AcmeAISDK::Models::FileFileCreateParams::ProcessingOptions?

      def processing_options=: (
        AcmeAISDK::Models::FileFileCreateParams::ProcessingOptions
      ) -> AcmeAISDK::Models::FileFileCreateParams::ProcessingOptions

      def initialize: (
        file: IO | StringIO,
        ?description: String,
        ?processing_options: AcmeAISDK::Models::FileFileCreateParams::ProcessingOptions,
        ?request_options: AcmeAISDK::request_opts
      ) -> void

      def to_hash: -> AcmeAISDK::Models::file_file_create_params

      type processing_options = { language: String, ocr: bool }

      class ProcessingOptions < AcmeAISDK::Internal::Type::BaseModel
        attr_reader language: String?

        def language=: (String) -> String

        attr_reader ocr: bool?

        def ocr=: (bool) -> bool

        def initialize: (?language: String, ?ocr: bool) -> void

        def to_hash: -> AcmeAISDK::Models::FileFileCreateParams::processing_options
      end
    end
  end
end
